// Generated by scripts/generate-blur-data.mjs - do not edit manually.

export const imageBlurData: Record<string, string> = {
  "/avatar.webp": "data:image/webp;base64,UklGRmQAAABXRUJQVlA4IFgAAAAwAgCdASoQABAABUB8JQBdj+ACuODHUTLcsAD+yWTjJ8KKPV3qMypFXDlA2s/+QD0SWvIQ+eWhL12aUdTDirmPibh9YYRBnmXVff29kGArbNrgvq1zCIAA",
  "/projects/TvShow/TvShowApp-1.png": "data:image/webp;base64,UklGRkwAAABXRUJQVlA4IEAAAADQAQCdASoQAAoABUB8JYwAAl1r7/p02AD+SMPj95qpfDvBxCq5UnNF60ybHuqOJ0Gydobxguyqm3HOXuKwAAAA",
  "/projects/TvShow/TvShowApp-2.png": "data:image/webp;base64,UklGRqgAAABXRUJQVlA4IJwAAABQBACdASoQACkAPzmGvVQvKKajKqwB4CcJQBmDgsyZkIlL2CJvVjT/PoGAAP5BLlW44oU5uvRFSnVdkmnGtj8HuXcOpqY08pcRrNm+2KOreE6a11zOv54MKIzgtVB+jqnHUwwn28EFmrJac73Nit4GDCZvm60CH2m5lyT0jsq6KVs9LVQC1LUAOphLU7peqI3Hkyv6XGH0GziAAAA=",
  "/projects/TvShow/TvShowApp-3.png": "data:image/webp;base64,UklGRqYAAABXRUJQVlA4IJoAAACQBACdASoQACgAPyV4sVOuJySitUgBwCSJQBm4BZrMtAkUGqi5VvBvydwMTYAA/ujahGCaXkyfg0HGrAx5Q5sFpi/XQ84wZhfWOzDXCZyPZGCaxsfbgYklfnLjAJ6Lps2BjCZNUAxB90w8IxxHphIhK9HWxs2x0ku+u5CjtliTNhLpR1Z8bYie8TOtfODiD0R2sanXYsKF8AAA",
  "/projects/doors/Doors-1.png": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAAAwAQCdASoQAAMABUB8JaQAA3AA/vB80IqAAA==",
  "/projects/doors/Doors-2.png": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAAAwAQCdASoQAAMABUB8JaQAA3AA/vBkDjAAAA==",
  "/projects/doors/Doors-3.png": "data:image/webp;base64,UklGRiYAAABXRUJQVlA4IBoAAAAwAQCdASoQAAMABUB8JaQAA3AA/vBkDjAAAA==",
  "/projects/doors/Doors-4.png": "data:image/webp;base64,UklGRkYAAABXRUJQVlA4IDoAAACwAQCdASoQAAsABUB8JYwAAuQaZFgAAP7rMbVxWaIKc6zF4DLct5z52Op5m04D+TP40gTWM6zflEAA",
  "/projects/flowboard/Flowboard-1.png": "data:image/webp;base64,UklGRiwAAABXRUJQVlA4ICAAAABQAQCdASoQAAoABUB8JZwABAAAAP7v43+1NWuKjZAAAA==",
  "/projects/flowboard/Flowboard-2.png": "data:image/webp;base64,UklGRi4AAABXRUJQVlA4ICIAAAAwAQCdASoQAA8ABUB8JZwAA3AA/vA+ZMCRoCg3ONqAUAAA",
  "/projects/lerni/Lerni-1.png": "data:image/webp;base64,UklGRioAAABXRUJQVlA4IB4AAAAwAQCdASoQAAoABUB8JaQAA3AA/u/J+kJubweAAAA=",
  "/projects/lerni/Lerni-2.png": "data:image/webp;base64,UklGRjQAAABXRUJQVlA4ICgAAAAwAQCdASoQAAoABUB8JaQAA3AA/vA8ue2/IN24fLvnp/DMNva+QAAA",
  "/projects/lerni/Lerni-3.png": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoABUB8JaQAA3AA/u/iLHXBuQAA",
  "/projects/lerni/Lerni-4.png": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoABUB8JaQAA3AA/u/iK+qu5AAA",
  "/projects/lerni/Lerni-5.png": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoABUB8JaQAA3AA/u/lja2LAAAA",
  "/projects/weseleo/weseleo-1.png": "data:image/webp;base64,UklGRj4AAABXRUJQVlA4IDIAAACwAQCdASoQAAoABUB8JZwAAeh0pucAAM2OsgoRwVLPvH1PqNR+NgTN5bNi2WMOVIAAAA==",
  "/projects/weseleo/weseleo-2.png": "data:image/webp;base64,UklGRigAAABXRUJQVlA4IBwAAAAwAQCdASoQAAoABUB8JaQAA3AA/vAzPfvOAAAA",
  "/projects/weseleo/weseleo-5.png": "data:image/webp;base64,UklGRlYAAABXRUJQVlA4IEoAAABQAwCdASoQABoAPzmQvlWvKqajMAgB4CcJaVTAAIqjtn4mAAD+9IDWP35T2J/nyBtevqlwQFxzUZnCrl3LgjmJ1c+9i2D5PoAAAA==",
  "/projects/weseleo/weseleo-6.png": "data:image/webp;base64,UklGRkoAAABXRUJQVlA4ID4AAAAwAwCdASoQABoAPzmQvlWvKqajMAgB4CcJaQAAelksd43gAP7uayORPRXwIH4sg9/iuRSy0hmvwRD5L7QAAA=="
};
